theme: 
    - hugo-theme-novela
    - hugo-shortcode-gallery
baseURL: "https://example.com"
languageCode: "en-us"
title: "Aman Bhargava"
pygmentsstyle: 'monokai'
paginate: 6
social:
  twitter: "https://twitter.com/thedivtagguy"
  github: "https://github.com/thedivtagguy"
  instagram: "https://instagram.com/thedivtagguy"
taxonomies:
  author: authors
params:
    galleryRowHeight    : 200
    galleryMargins      : 10
    galleryResizeOptions: "800x800 q88 Lanczos"
    galleryPreviewType  : "blur"
    galleryThumbnailHoverEffect : "enlarge"

imaging.exif:
    includeFields : ".*"
